syntax = "proto3";

package data;

option go_package = "/src/proto";

service DataService {
    rpc ProcessData (DataRequest) returns (DataResponse);
}

message DataRequest {
    string sellerId = 1;
}

message DataResponse {
    int32 activeProductsAge = 1;
    int32 orderCancellationBeforeConfirmation = 2;
    int32 orderCancellationDuringDelivery = 3;
    int32 orderConfirmationTimeViolation = 4;
    int32 orderAssemblyTimeViolation = 5;
    int32 deliveryTimeViolation = 6;
    double sellerRating = 7;
    int32 turnover = 8;
    bool isCreditBuyButton = 9;
    bool isQRCreditOffline = 10;
}
